analyzer:
  errors:
    use_build_context_synchronously: ignore
    unnecessary_null_comparison: ignore
    library_private_types_in_public_api: ignore
    deprecated_member_use: ignore
    depend_on_referenced_packages: ignore
include: package:flutter_lints/flutter.yaml

linter:

  rules:
    avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
